// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/briefings/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/briefings/[id]/index').default>>>>
    }
    '/api/briefings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/briefings/index').default>>>>
    }
    '/api/briefings/new': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/briefings/new/index').default>>>>
    }
    '/api/users/briefings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/briefings/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/session': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@sidebase/nuxt-session/dist/runtime/server/api/session.patch').default>>>>
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@sidebase/nuxt-session/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@sidebase/nuxt-session/dist/runtime/server/api/session.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@sidebase/nuxt-session/dist/runtime/server/api/session.post').default>>>>
    }
    '/mail/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-mail/dist/server-handler.post').default>>>>
    }
  }
}
export {}